apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public

commonLabels:
  app: public-api-production
  team: gpro

commonAnnotations:
  note: This is an production deployment

resources:
- ns.yaml
- ../../base

  #inline 

  #archivo yaml
patches:
- patch: |
    - op: add
      path: /spec/type
      value: ClusterIP
  target:
    name: svc-public-api
- patch: |
    - op: replace
      path: /spec/replicas
      value: 4
  target:
    kind: Deployment
    name: public-api
- path: cm-patch-prod.yaml
  target:
    name: cm-private-api
- path: ing-patch-prod.yaml
  target:
    kind: Ingress
    name: public-api


images:
- name: KUSTOMIZE-DEFINED
  newName: rmsql248/kubelabs_publicapi2
  newTag: 3.1.0
