apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels:
  app: public-api-stage
  team: devops

commonAnnotations:
  note: "This is an stage deployment"

resources:
  - ns.yaml
  - ../../base

patchesStrategicMerge:
  - deploy-merge.yaml

patches: 
  #inline 
  - target: 
      name: svc-public-api
    patch: |
      - op: add
        path: /spec/type
        value: ClusterIP

  #archivo yaml
  - target:
      name: cm-private-api
    path: cm-patch.yaml
  - target:
      name: public-api
      kind: Ingress
    path: ing-patch.yaml


images: 
  - name: KUSTOMIZE-DEFINED
    newName: rmsql248/kubelabs_publicapi2
    newTag: 1.0.0
