apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

commonLabels:
  app: public-api-stage
  team: devops

commonAnnotations:
  note: This is an stage deployment

resources:
- ns.yaml
- ../../base

patchesStrategicMerge:
- deploy-merge.yaml

  #inline 

  #archivo yaml
patches:
- patch: |
    - op: add
      path: /spec/type
      value: ClusterIP
  target:
    name: svc-public-api
- path: cm-patch.yaml
  target:
    name: cm-private-api
- path: ing-patch.yaml
  target:
    kind: Ingress
    name: public-api


images:
- name: KUSTOMIZE-DEFINED
  newName: rmsql248/kubelabs_publicapi2
  newTag: 2.0.0
